version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - ./adj:/app/adj
    ports:
      - "8080:8080"
    environment:
      - CGO_ENABLED=1
    command: sh -c "cd cmd && go run ."

  # Ethernet View
  ethernet-view:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./ethernet-view:/app
      - ./common-front:/common-front
    ports:
      - "5174:5174"
    command: sh -c "npm install && npm run dev -- --host"

  # Control Station
  control-station:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./control-station:/app
      - ./common-front:/common-front
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

  # Common front (for building)
  common-front:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./common-front:/app
    command: sh -c "npm install && npm run build && npm run dev"