packages:
  # frontend
  - frontend/frontend-kit/**
  - frontend/testing-view
  - frontend/competition-view
  - frontend/flashing-view

  # Backend packages
  - "backend"
  - "blcu-programming"
  
  # Electron packages
  - "electron-app"
  - "e2e"

