packages:
  # Frontend packages
  - "frontend/frontend-kit/**"
  - "frontend/testing-view"
  - "frontend/competition-view"
  - "frontend/logging-view"
  - "frontend/flashing-view"
  - "frontend/adj-view"

  # Backend packages
  - "backend"
  - "blcu-programming"
  
  # Electron packages
  - "electron-app"
  - "e2e"

