FROM golang:1.21-alpine

RUN apk add --no-cache gcc musl-dev libpcap-dev pkgconfig

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["sh", "-c", "cd cmd && go run ."]