
[server.local]
address = "127.0.0.1:4000"
static = "./static"

[server.local.endpoints]
pod_data = "/podDataStructure"
order_data = "/orderStructures"
programable_boards = "/uploadableBoards"
connections = "/backend"
files = "/"

[vehicle]
boardsList = ["VCU"]

[adj]
branch = "main" # Leave blank when using ADJ as a submodule
