# Hyperloop UPV Backend Configuration
# Configuration file for the H10 Control Station backend server

# Vehicle Configuration
[vehicle]
boards = ["HVSCU", "PCU", "BLCU"]

# BLCU (Boot Loader Control Unit) Configuration
[blcu]
ip = "127.0.0.1"      # TFTP server IP address
download_order_id = 1 # Packet ID for download orders (0 = use default)
upload_order_id = 2   # Packet ID for upload orders (0 = use default)

# Server Configuration
[server.ethernet-view]
address = "127.0.0.1:4040"
static = "./ethernet-view"

[server.ethernet-view.endpoints]
pod_data = "/podDataStructure"
order_data = "/orderStructures"
programable_boards = "/uploadableBoards"
connections = "/backend"
files = "/"

[server.control-station]
address = "127.0.0.1:4000"
static = "./control-station"

[server.control-station.endpoints]
pod_data = "/podDataStructure"
order_data = "/orderStructures"
programable_boards = "/uploadableBoards"
connections = "/backend"
files = "/"

# ADJ (Architecture Description JSON) Configuration
[adj]
branch = "software" # Leave blank when using ADJ as a submodule (like this: "")
test = true         # Enable test mode

# Network Configuration
[network]
manual = true # Manual network device selection

# Transport Configuration
[transport]
propagate_fault = true

[tftp]
block_size = 131072   # TFTP block size in bytes (128kB)
retries = 3          # Maximum number of retries before aborting transfer
timeout_ms = 5000    # Timeout between retries in milliseconds
backoff_factor = 2   # Backoff multiplier for retry delays
enable_progress = true # Enable progress callbacks during transfers
