[vehicle]
boards = ["HVSCU", "PCU"]
[server.ethernet-view]
address = "127.0.0.1:4040"
static = "./ethernet-view"
[server.ethernet-view.endpoints]
pod_data = "/podDataStructure"
order_data = "/orderStructures"
programable_boards = "/uploadableBoards"
connections = "/backend"
files = "/"
[server.control-station]
address = "127.0.0.1:4000"
static = "./control-station"
[server.control-station.endpoints]
pod_data = "/podDataStructure"
order_data = "/orderStructures"
programable_boards = "/uploadableBoards"
connections = "/backend"
files = "/"
[adj]
branch = "main" # Leave blank when using ADJ as a submodule (like this: "")
test = true
[network]
manual = false
[transport]
propagate_fault = true

[tftp]
block_size = 512      # TFTP block size in bytes (default: 512)
retries = 3          # Maximum number of retries before aborting transfer
timeout_ms = 5000    # Timeout between retries in milliseconds
backoff_factor = 2   # Backoff multiplier for retry delays
enable_progress = true # Enable progress callbacks during transfers
