# DEV MODE CONFIGURATION FILE
# This configuration enables dev mode for easier local development
# Dev mode uses a UDP server instead of packet sniffing, removing the need for sudo

# <-- CHECKLIST -->
# 1. Check that all the boards you want to use are declared in the [vehicle] section
# 2. Set the branch you want to use for the ADJ configuration
# 3. Toggle the Fault Propagation to your needs (true/false)
# 4. Check the TCP configuration and make sure to use the needed Keep Alive settings

# Control Station general configuration
[app]
automatic_window_opening = "" # Leave blank to open no windows (<blank>, ethernet-view, control-station, both)

# Vehicle Configuration
[vehicle]
boards = ["HVSCU", "HVSCU-cabinet", "PCU", "LCU", "BCU", "BMSL"]

# ADJ (Architecture Description JSON) Configuration
[adj]
branch = "software" # Leave blank when using ADJ as a submodule (like this: "")
test = true         # Enable test mode

# Network Configuration
[network]
manual = false  # Manual network device selection
dev_mode = true # IMPORTANT: Dev mode enabled - uses UDP server instead of packet sniffer

# Transport Configuration
[transport]
propagate_fault = false

# TCP Configuration
# These settings control how the backend reconnects to boards when connections are lost
[tcp]
backoff_min_ms = 999999        # Minimum backoff duration in milliseconds
backoff_max_ms = 999999        # Maximum backoff duration in milliseconds
backoff_multiplier = 1         # Exponential backoff multiplier (e.g., 1.5 means each retry waits 1.5x longer)
max_retries = 0                # Maximum retries before cycling (0 = infinite retries, recommended for persistent reconnection)
connection_timeout_ms = 999999 # Timeout for the initial connection attempt
keep_alive_ms = 0              # Keep-alive interval in milliseconds (0 to disable)

# Server Configuration
[server.ethernet-view]
address = "127.0.0.1:4040"
static = "./ethernet-view"

[server.ethernet-view.endpoints]
pod_data = "/podDataStructure"
order_data = "/orderStructures"
programable_boards = "/uploadableBoards"
connections = "/backend"
files = "/"

[server.control-station]
address = "127.0.0.1:4000"
static = "./control-station"

[server.control-station.endpoints]
pod_data = "/podDataStructure"
order_data = "/orderStructures"
programable_boards = "/uploadableBoards"
connections = "/backend"
files = "/"

# TFTP Configuration
[tftp]
block_size = 512       # TFTP block size (512 or 1468 bytes)
retries = 3            # Number of retries for TFTP operations
timeout_ms = 5000      # Timeout for TFTP operations in milliseconds
backoff_factor = 2     # Backoff factor for retries
enable_progress = true # Enable progress updates during transfers

# BLCU Configuration
[blcu]
ip = "10.10.10.5"     # BLCU IP address
download_order_id = 0 # Order ID for download operations (0 = use default)
upload_order_id = 0   # Order ID for upload operations (0 = use default)

# Logging Configuration
[logging]
level = "debug"      # Logging level (trace, debug, info, warn, error, fatal)
console = true       # Enable console output
file = "backend.log" # Log file path (empty to disable file logging)
max_size_mb = 100    # Maximum log file size in MB
max_backups = 3      # Number of backup files to keep
max_age_days = 7     # Maximum age of log files in days
