
export enum BmslMeasurements {
    avCurrent = "BMSL/AV_current",
    lowCell1 = "BMSL/low_cell1",
    lowCell2 = "BMSL/low_cell2",
    lowCell3 = "BMSL/low_cell3",
    lowCell4 = "BMSL/low_cell4",
    lowCell5 = "BMSL/low_cell5",
    lowCell6 = "BMSL/low_cell6",
    lowSOC1 = "BMSL/low_SOC1",
    lowIsBalancing1 = "BMSL/low_is_balancing1",
    lowMaximumCell = "BMSL/low_maximum_cell",
    lowMinimumCell = "BMSL/low_minimum_cell",
    lowBatteryTemperature1 = "BMSL/low_battery_temperature_1",
    lowBatteryTemperature2 = "BMSL/low_battery_temperature_2",
    totalVoltageLow = "BMSL/total_voltage_low",
    inputChargingCurrent = "BMSL/input_charging_current",
    outputChargingCurrent = "BMSL/output_charging_current",
    inputChargingVoltage = "BMSL/input_charging_voltage",
    outputChargingVoltage = "BMSL/output_charging_voltage",
    pwmFrequency = "BMSL/pwm_frequency",
    conditionsReady = "BMSL/conditions_ready",
    conditionsWantToCharge = "BMSL/conditions_want_to_charge",
    conditionsCharging = "BMSL/conditions_charging",
    conditionsFault = "BMSL/conditions_fault"
}