export const BmslMeasurements = {
    cell1: 'BMSL/cell_1',
    cell2: 'BMSL/cell_2',
    cell3: 'BMSL/cell_3',
    cell4: 'BMSL/cell_4',
    cell5: 'BMSL/cell_5',
    cell6: 'BMSL/cell_6',
    tempMin: 'BMSL/temp_min',
    tempMax: 'BMSL/temp_max',
    voltageMin: 'BMSL/voltage_min',
    voltageMax: 'BMSL/voltage_max',
    totalVoltage: 'BMSL/total_voltage',
    dischargeCurrent: 'BMSL/avionics_current',
    current: 'BMSL/current',
    stateOfCharge: 'BMSL/SOC',
    generalState: 'BMSL/general_state',
};
