export const BmslMeasurements = {
    cell1: 'BMSL/low_cell_voltage_1',
    cell2: 'BMSL/low_cell_voltage_2',
    cell3: 'BMSL/low_cell_voltage_3',
    cell4: 'BMSL/low_cell_voltage_4',
    cell5: 'BMSL/low_cell_voltage_5',
    cell6: 'BMSL/low_cell_voltage_6',
    temp1: 'BMSL/low_temp_1',
    temp2: 'BMSL/low_temp_2',
    totalVoltage: 'BMSL/total_voltage',
    dischargeCurrent: 'BMSL/avionics_current',
    current: 'BMSL/current',
    stateOfCharge: 'BMSL/SOC',
    generalState: 'BMSL/general_state',
};
