export const LcuMeasurements = {
    coilCurrentHEMS1: 'LCU/lcu_coil_current_1',
    coilCurrentHEMS2: 'LCU/lcu_coil_current_2',
    coilCurrentHEMS3: 'LCU/lcu_coil_current_3',
    coilCurrentHEMS4: 'LCU/lcu_coil_current_4',
    coilCurrentEMS1: 'LCU/lcu_coil_current_5',
    coilCurrentEMS2: 'LCU/lcu_coil_current_6',
    coilCurrentEMS3: 'LCU/lcu_coil_current_7',
    coilCurrentEMS4: 'LCU/lcu_coil_current_8',
    coilCurrentEMS5: 'LCU/lcu_coil_current_9',
    coilCurrentEMS6: 'LCU/lcu_coil_current_10',
    coilTemperatureHEMS1: 'LCU/lcu_coil_temp_1',
    coilTemperatureHEMS2: 'LCU/lcu_coil_temp_2',
    coilTemperatureHEMS3: 'LCU/lcu_coil_temp_3',
    coilTemperatureHEMS4: 'LCU/lcu_coil_temp_4',
    coilTemperatureEMS1: 'LCU/lcu_coil_temp_5',
    coilTemperatureEMS2: 'LCU/lcu_coil_temp_6',
    coilTemperatureEMS3: 'LCU/lcu_coil_temp_7',
    coilTemperatureEMS4: 'LCU/lcu_coil_temp_8',
    coilTemperatureEMS5: 'LCU/lcu_coil_temp_9',
    coilTemperatureEMS6: 'LCU/lcu_coil_temp_10',
    verticalAirgap1: 'LCU/lcu_airgap_1',
    verticalAirgap2: 'LCU/lcu_airgap_2',
    verticalAirgap3: 'LCU/lcu_airgap_3',
    verticalAirgap4: 'LCU/lcu_airgap_4',
    horizontalAirgap1: 'LCU/lcu_airgap_5',
    horizontalAirgap2: 'LCU/lcu_airgap_6',
    horizontalAirgap3: 'LCU/lcu_airgap_7',
    horizontalAirgap4: 'LCU/lcu_airgap_8',
    positionY: 'LCU/dist_control_y',
    positionZ: 'LCU/dist_control_z',
    rotationPitch: 'LCU/rot_control_y',
    rotationRoll: 'LCU/rot_control_x',
    rotationYaw: 'LCU/rot_control_z',
    generalState: 'LCU/general_state',
    busVoltage1: 'LCU/lcu_vbat_1',
    busVoltage2: 'LCU/lcu_vbat_2',
    busVoltage3: 'LCU/lcu_vbat_3',
    busVoltage4: 'LCU/lcu_vbat_4',
    busVoltage5: 'LCU/lcu_vbat_5',
    busVoltage6: 'LCU/lcu_vbat_6',
    busVoltage7: 'LCU/lcu_vbat_7',
    busVoltage8: 'LCU/lcu_vbat_8',
    busVoltage9: 'LCU/lcu_vbat_9',
    busVoltage10: 'LCU/lcu_vbat_10',
};

export const LcuOrders = {
    startLevitationControl: 355,
    startVerticalLevitation: 356,
    startHorizontalLevitation: 360,
    stopLevitation: 357,
};
