export const PcuMeasurements = {
    motorAPeakCurrent: 'PCU/peak_current',
    podPosition: 'PCU/encoder_position',
    motorACurrentU: 'PCU/current_sensor_u_a',
    motorACurrentV: 'PCU/current_sensor_v_a',
    motorACurrentW: 'PCU/current_sensor_w_a',
    motorATemp: 'PCU/motor_a_temp_u',
    motorBPeakCurrent: 'PCU/peak_current',
    motorBCurrentU: 'PCU/current_sensor_u_b',
    motorBCurrentV: 'PCU/current_sensor_v_b',
    motorBCurrentW: 'PCU/current_sensor_w_b',
    motorBTemp: 'PCU/motor_b_temp_v',
    frequency: 'PCU/target_frequency',
    generalState: 'PCU/general_state',
    specificState: 'PCU/operating_state',
};