export enum VcuMeasurements {
    reed1 = 'VCU/reed1',
    reed2 = 'VCU/reed2',
    reed3 = 'VCU/reed3',
    reed4 = 'VCU/reed4',
    allReeds = 'VCU/all_reeds',
    highPressure = 'VCU/high_pressure',
    lowPressure1 = 'VCU/low_pressure_1',
    lowPressure2 = 'VCU/low_pressure_2',
    valveState = 'VCU/valve_state',
    referencePressure = 'VCU/reference_pressure',
    position = 'PCU/speetec_position',
    speed = 'PCU/speetec_velocity',
    acceleration = 'PCU/speetec_accel',
    pcuConnection = 'VCU/PCU_connection',
    obccuConnection = 'VCU/OBCCU_connection',
    lcuConnection = 'VCU/LCU_connection',
    bmslConnection = 'VCU/BMSL_connection',
    generalState = 'VCU/general_state',
    operationalState = 'VCU/operational_state',
    regulatorPressure = 'VCU/regulator_pressure',
    pressureHigh = 'VCU/pressure_high',
    pressureBrakes = 'VCU/pressure_brakes',
    pressureCapsule = 'VCU/pressure_capsule'
}
