name: Build updater

on:
  workflow_dispatch:
  pull_request:
    paths:
      - updater/**

jobs:
  build-updater-linux:
    name: "Build updater for Linux"
    runs-on: ubuntu-latest

    container:
      image: golang:alpine

    env:
      UPDATER_DIR: ./updater

    steps:
    - name: Install packages (incl. git!)
      run: |
        apk update
        apk add --no-cache gcc go git

    - uses: actions/checkout@v4

    - name: Create output path
      working-directory: ${{ env.UPDATER_DIR }}
      run: mkdir -p output

    - name: Build (64-bit Linux)
      working-directory: ${{ env.UPDATER_DIR }}
      env:
        CGO_ENABLED: 1
        GOARCH: amd64
        GOOS: linux
      run: |
        go build -ldflags '-linkmode external -extldflags "-static"' \
          -o output/updater-linux-64

    - name: Upload Linux build
      uses: actions/upload-artifact@v4
      with:
        name: updater-linux
        path: ${{ env.UPDATER_DIR }}/output/*
        retention-days: 3
        compression-level: 9

  build-updater-windows:
    name: "Build updater for Windows"
    runs-on: windows-latest

    env:
      UPDATER_DIR: .\\updater

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go (with cache)
      uses: actions/setup-go@v4
      with:
        go-version: "1.21.3"
        cache-dependency-path: updater\\go.sum

    - name: Create output path
      working-directory: ${{ env.UPDATER_DIR }}
      run: mkdir output

    - name: Build (64-bit Windows)
      working-directory: ${{ env.UPDATER_DIR }}
      env:
        CGO_ENABLED: 1
        GOARCH: amd64
        GOOS: windows
      run: go build -o output\\updater-windows-64.exe

    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: updater-windows
        path: ${{ env.UPDATER_DIR }}\\output\\*
        retention-days: 3
        compression-level: 9

  build-updater-mac:
    name: "Build updater for macOS"
    runs-on: macos-latest

    env:
      UPDATER_DIR: ./updater

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go (with cache)
      uses: actions/setup-go@v4
      with:
        go-version: "1.21.3"
        cache-dependency-path: updater/go.sum

    - name: Create output path
      working-directory: ${{ env.UPDATER_DIR }}
      run: mkdir -p output

    - name: Build (Intel macOS)
      working-directory: ${{ env.UPDATER_DIR }}
      env:
        CGO_ENABLED: 1
        GOARCH: amd64
        GOOS: darwin
      run: go build -o output/updater-macos-64

    - name: Build (Apple Silicon)
      working-directory: ${{ env.UPDATER_DIR }}
      env:
        CGO_ENABLED: 1
        GOARCH: arm64
        GOOS: darwin
      run: go build -o output/updater-macos-m1-64

    - name: Upload macOS build
      uses: actions/upload-artifact@v4
      with:
        name: updater-macos
        path: ${{ env.UPDATER_DIR }}/output/*
        retention-days: 3
        compression-level: 9
