name: Frontend Tests

on:
  pull_request:
    branches:
      - main
      - develop
      - production
      - "frontend/**"
      - "testing-view/**"
      - "competition-view/**"
    paths:
      - "frontend/**"
      - "pnpm-lock.yaml"
      - ".github/workflows/frontend-tests.yaml"

jobs:
  test:
    name: Run Frontend Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --filter=testing-view --filter=flashing-view --filter=competition-view --filter=ui --filter=core

      - name: Build frontend
        run: pnpm build --filter="./frontend/**"

      - name: Run tests
        run: pnpm test --filter="./frontend/**"
