name: Test backend

on:
    push:
      paths:
        - backend/**
    pull_request:
      paths:
        - backend/**
    workflow_dispatch:

jobs:
  test-backend:
    name: "Test backend"
    runs-on: ubuntu-latest

    env:
      BACKEND_DIR: ./backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          cache: false
          

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libpcap-dev

      - name: Test with Go
        working-directory: "${{env.BACKEND_DIR}}"
        run: go test -v -timeout 30s ./...
